const categories = [
  "Agrarhandel",
  "Baustoffhandel",
  "Bauwesen",
  "Einzelhandel/Raiffeisen",
  "Energie",
  "Futtermittel/Tierernährung",
  "IT",
  "Kaufmännisch/Administrativ",
  "Landtechnik",
  "Logistik/Transport",
  "Personal",
  "Pflanzenbau",
  "Produktion",
  "Sonstiges",
  "Vertrieb/Marketing",
];

/*PLZ ALS STRING WEGEN PLZs MIT 0 VORNE*/

const data = [
  {
    title: "Einzelhandelskaufmann für den Bereich Garten und Heimtier (m/w/d)",
    company: "AGRAVIS RAIFFEISEN-MARKT GMBH",
    city: "Haßloch",
    date: "22. Juni 2020",
    plz: "67454",
    category: categories[3],
    desc: "Einzelhandelskaufmann",
  },
  {
    title: "Auszubildender zum Kaufmann im Groß- und Außenhandel (m/w/d)",
    company: "AGRAVIS KORNHAUS OSTWESTFALEN GMBH",
    city: "Warburg-Hohenwepel",
    date: "22. Juni 2020",
    plz: "34414",
    category: categories[3],
    desc: "Auszubildender zum Kaufmann",
  },
  {
    title: "Käufmännischer Mitarbeiter (m/w/d)",
    company: "BARO LAGERHAUS GMBH & CO. KG",
    city: "Aschersleben",
    date: "22. Juni 2020",
    plz: "06449",
    category: categories[3],
    desc: "Käufmännischer Mitarbeiter",
  },
  {
    title:
      "Ingenieur / Techniker für das Arbeitsgebiet Arbeitssicherheit und Umweltschutz (m/w/d)",
    company: "VERAVIS GMBH",
    city: "Hannover",
    date: "19. Juni 2020",
    plz: "30159",
    category: categories[8],
    desc: "Ingenieur / Techniker",
  },
  {
    title: "Sachbearbeiter Raiffeisenmärkte (m/w/d)",
    company: "AGRAVIS RAIFFEISEN AG",
    city: "Münster",
    date: "18. Juni 2020",
    plz: "48143",
    category: categories[7],
    desc: "Sachbearbeiter",
  }, {
    title: "IT-Businesspartner (m/w/d)",
    company: "AGRAVIS RAIFFEISEN AG",
    city: "Münster",
    date: "18. Juni 2020",
    plz: "48143",
    category: categories[6],
    desc: "IT-Businesspartner",
  }, {
    title: "Lagermitarbeiter (m/w/d) Silo",
    company: "RÖRIG/HARTIG U. CO. LANDWARENHANDEL GMBH",
    city: "Wolfhagen",
    date: "17. Juni 2020",
    plz: "34466",
    category: categories[9],
    desc: "Lagermitarbeiter",
  },
  {
    title: "Produktions- und Managementberater Rind im Außendienst (m/w/d)",
    company: "AGRAVIS MISCHFUTTER WEST GMBH",
    city: "Sundern",
    date: "17. Juni 2020",
    plz: "59846",
    category: categories[12],
    desc: "Produktions- und Managementberater",
  },
  {
    title: "Programmierer (m/w/d)",
    company: "BARO LAGERHAUS GMBH & CO. KG",
    city: "Bülstringen",
    date: "17. Juni 2020",
    plz: "39340",
    category: categories[6],
    desc: "Programmierer",
  },
  {
    title: "Anlagenmechaniker (m/w/d) SHK",
    company: "PIENING HAUSTECHNIK UND ENERGIESERVICE GMBH",
    city: "Göttingen",
    date: "17. Juni 2020",
    plz: "37073",
    category: categories[12],
    desc: "Anlagenmechaniker",
  },
];

exports.data = data;

/*
0 "Agrarhandel",
1 "Baustoffhandel",
2 "Bauwesen",
3 "Einzelhandel/Raiffeisen",
4 "Energie",
5 "Futtermittel/Tierernährung",
6 "IT",
7 "Kaufmännisch/Administrativ",
8 "Landtechnik",
9 "Logistik/Transport",
10 "Personal",
11 "Pflanzenbau",
12 "Produktion",
13 "Sonstiges",
14 "Vertrieb/Marketing",
*/
